version: '3'
volumes: 
  data:
services: 
  mydbserver:
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes: 
      - ./frontend:/usr/share/nginx/html/
    ports: 
      - 80:80
  backend:
    image: python:3.6
    volumes: 
      - ./backend:/backend
    working_dir: /backend
    command: ./app.sh
    ports: 
      - 8080:8080
