version: '3'
volumes: 
  data:
services: 
  mydbserver:
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
